export const LANGUAGE="LANGUAGE";
export const ACCOUNT="ACCOUNT";
export const LOGOUT="LOGOUT";
export const POSTAUCTION="POSTAUCTION";
export const ALL_AUCTION="ALLAUCTION";
export const ALL_EXCEPT_AUCTIONER="ALLEXCEPT";
export const GET_AUCTION_BY_AUCTIONER="GETAUCTIONBYAUCTIONER";
export const POPULAR_AUCTION="POPULAR";
export const CATAGORY_AUCTION='CATAGORY';
export const AUCTION_BY_ID="AUCTION_BY_ID";
export const LATEST_AUCTION="ACUTION_AUCTION";
export const BID_AUCTION="BID_AUCTION";
export const SEARCH_AUCTION="SEARCH_AUCTION";
export const ACCOUNTCHECKOUT='ACCOUNTCHECKOUT';
export const CLEANUPPOSTAUCTION="CLEANUPPOSTAUCTION";
export const CLEANUPBIDAUCTION="CLEANUPBIDAUCTION";
export const GET_BID_AUCTION="GET_BID_AUCTION";
export const GET_NOTIFICATION="GET_NOTIFICATION";
export const DEPOSIT="DEPOSIT";
export const WITHDRAW="WITHDRAW";
export const DEPOSITCLEANUP="DEPOSITCLEANUP";
export const WITHDRAWCLEANUP='WITHDRAWCLEANUP';
export const UPDATEBALANCE="UPDATEBALANCE";
export const USERPROFILE="USERPROFILE";
export const UPDATEPROFILE="UPDATEPROFILE";
export const BACKENDURL="http://localhost:5000";



