export const LANGUAGE="LANGUAGE";
export const ACCOUNT="ACCOUNT";
export const LOGOUT="LOGOUT";
export const POSTAUCTION="POSTAUCTION";
export const ALL_AUCTION="ALLAUCTION";
export const ALL_EXCEPT_AUCTIONER="ALLEXCEPT";
export const GET_AUCTION_BY_AUCTIONER="GETAUCTIONBYAUCTIONER";
export const POPULAR_AUCTION="POPULAR";
export const CATAGORY_AUCTION='CATAGORY';
export const AUCTION_BY_ID="AUCTION_BY_ID";
export const LATEST_AUCTION="ACUTION_AUCTION";
export const BID_AUCTION="BID_AUCTION";
export const SEARCH_AUCTION="SEARCH_AUCTION";


